site_name: Canvas LMS Automation
site_url: https://chartorresgg.github.io/canvas-automation/
repo_url: https://github.com/chartorresgg/canvas-automation
docs_dir: docs

theme:
  name: material
  language: es
  
markdown_extensions:
  - admonition
  - pymdownx.details

validation:
  links:
    unrecognized_links: warn
    anchors: warn